# netlify.toml en la raíz de tu proyecto

[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  external_node_modules = ["pdf2json", "googleapis", "openai"]
